parameters:
    env(PERSOO_API_URL): 'https://rtp.persoo.ai/'
    env(PERSOO_ACCOUNT_ID): ''
    env(PERSOO_IS_PRODUCTION_MODE): 'false'
    env(PERSOO_RECOMMENDATION_ALGORITHM_ID): ''
    persoo.recommendation.algorithm_id: '%env(PERSOO_RECOMMENDATION_ALGORITHM_ID)%'
    env(PERSOO_RECOMMENDATION_OFFER_ID): ''
    persoo.recommendation.offer_id: '%env(PERSOO_RECOMMENDATION_OFFER_ID)%'
    env(PERSOO_RECOMMENDATION_LOCATION_ID): ''
    persoo.recommendation.location_id: '%env(PERSOO_RECOMMENDATION_LOCATION_ID)%'
    env(PERSOO_SEARCH_ALGORITHM_ID): ''
    persoo.search.algorithm_id: '%env(PERSOO_SEARCH_ALGORITHM_ID)%'
    env(PERSOO_SEARCH_OFFER_ID): ''
    persoo.search.offer_id: '%env(PERSOO_SEARCH_OFFER_ID)%'
    env(PERSOO_SEARCH_LOCATION_ID): ''
    persoo.search.location_id: '%env(PERSOO_SEARCH_LOCATION_ID)%'
    env(PERSOO_ENABLED_DOMAIN_IDS): ''
    persoo.enabled_domain_ids: '%env(PERSOO_ENABLED_DOMAIN_IDS)%'
